version: "3.8"

services:
  web:
    build: .
    container_name: fastapi_app
    volumes:
      - ./app:/app
    expose:
      - 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - nginx

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

  backup:
    build:
      context: ./backup
    volumes:
      - ./app:/app
    command: ["sh", "backup.sh"]

  update:
    build:
      context: ./update
    volumes:
      - ./app:/app
    command: ["sh", "update.sh"]

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  portainer_data:
  elastic_data:
